### ISSUE TITLE
Проблема преобразования 

### ISSUE THREAD

**Issue by CactysFedya** [denisbondar/rknn-converter#1]
Добрый день! Возникает вот такая проблема, когда я хочу преобразовать ПОЛЬЗОВАТЕЛЬСКУЮ модель из формата ONNX в формат RKNN.
E RKNN: [16:41:14.271] REGTASK: The bit width of field value exceeds the limit, target: v2, offset: 0x4030, shift = 0, limit: 0x1fff, value: 0x20cf
E RKNN: [16:41:14.271] REGTASK: The bit width of field value exceeds the limit, target: v2, offset: 0x4030, shift = 0, limit: 0x1fff, value: 0x20cf
E RKNN: [16:41:14.271] REGTASK: The bit width of field value exceeds the limit, target: v2, offset: 0x4030, shift = 0, limit: 0x1fff, value: 0x20cf
E RKNN: [16:41:14.271] REGTASK: The bit width of field value exceeds the limit, target: v2, offset: 0x4030, shift = 0, limit: 0x1fff, value: 0x20cf
E RKNN: [16:41:14.271] REGTASK: The bit width of field value exceeds the limit, target: v2, offset: 0x4030, shift = 0, limit: 0x1fff, value: 0x20cf

**Comment by denisbondar** [comment]
Для конвертирования в ONNX (из YOLO) необходимо использовать специальную версию Ультралитикс [airockchip/ultralytics_yolov8](https://github.com/airockchip/ultralytics_yolov8.git)

Оригинальный Ультралитикс, на котором обучали модель, не подходит для последующего преобразования в RKNN.

В моем текущем репозитории уже есть нужная версия Ультралитикс и можно сконвертировать Yolo модель в RKNN формат (через ONNX) по инструкции из readme.

**Comment by CactysFedya** [comment]
Хорошо, спасибо. Тогда вопрос. Как обучить модель YOLO с версией для RKNN?

**Comment by denisbondar** [comment]
Разницы в обучении нет. Обучаете любым способом или для теста возьмите предобученную модель yolov8n.pt из репозитория [ultralitics/assets](https://github.com/ultralytics/assets/releases). После обучения получаете на выходе best.pt и преобразовываете его в специальный ONNX с шейпом как указано ниже и затем в RKNN.

При преобразовании в ONNX вы видите размер **output** шейпа.
```
PyTorch: starting from 'yolov8n.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) ...
```
Шейп, который _не подходит_ для RKNN, выглядит так: `(1, 84, 8400)`
Шейп, который _подходит_ для RKNN, выглядит так: `((1, 64, 80, 80), (1, 80, 80, 80), (1, 1, 80, 80), (1, 64, 40, 40), (1, 80, 40, 40), (1, 1, 40, 40), (1, 64, 20, 20), (1, 80, 20, 20), (1, 1, 20, 20))`

И еще одна, возможно важная деталь, моя сборка для версии RKNN-1.6. Сейчас уже вышла 2.1. Это не влияет на преобразование, но на NPU нужно также использовать версию 1.6.

**Comment by CactysFedya** [comment]
Спасибо. И последний вопрос. А как преобразовать в шейп с нужным выходом?

**Comment by CactysFedya** [comment]
С этим совсем я давно разобрался. Проблема была только в том, чтобы как "урезать" собственную обученную модель yolov8 с выходами ((1, 64, 80, 80), (1, 80, 80, 80), (1, 1, 80, 80), (1, 64, 40, 40), (1, 80, 40, 40), (1, 1, 40, 40), (1, 64, 20, 20), (1, 80, 20, 20), (1, 1, 20, 20)).
Я пытался обработать выход (1, 84, 8400), но у меня не вышло(

**Comment by denisbondar** [comment]
> А как преобразовать в шейп с нужным выходом?

Об этом писал в самом первом ответе.
Оригинальный ультралитикс не экспортирует в ONNX с нужным для RKNN шейпом.
Нужен специальный ультралитикс для RKNN.

**Comment by denisbondar** [comment]
В моей сборке используется специальный ультралитикс. Поэтому можно использовать просто мою сборку в отдельном виртуальном окружении, чтобы не конфликтовало с оригинальным Ультралитиксом.
Прочитайте описание как пользоваться в README

**Comment by CactysFedya** [comment]
Все понял. Спасибо огромное!

**Comment by denisbondar** [comment]
Пожалуйста.
